### ISSUE TITLE
Invalid webhook URL provided.

### ISSUE THREAD

**Issue by Amejame** [rtunaboss/TwitterMonitorV2#2]
I keep getting this error even if webhook is correct and everything works okay on other bots/monitors

**Comment by rtunazzz** [comment]
Hey!

Are you using the native, default webhooks? Sometimes when I would use Discord Canary/PTB webhooks, the webhook library would return errors.

Otherwise I tested the webhooks and everything works just fine. It would be a great help if you could send a screenshot/description of the error you're getting, if the mentioned above didn't solve the problem.

**Comment by Amejame** [comment]
Could you please give me your discord?
